version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/app
    command: python server.py

  telegrambot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - server
    command: python telegrambot.py