version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8100:8100"
    env_file:
      - ./.env
    volumes:
      - .:/app
    command: python server.py

  telegrambot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    extra_hosts:
      - "host.docker.internal:host-gateway
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - server
    command: python telegrambot.py